2024-03-06 00:16:18.356275: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-06 00:16:19.031062: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-06 00:16:19.032865: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-06 00:16:20.765192: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at openai-community/gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/huggingface_hub/utils/_deprecation.py:131: FutureWarning: 'Repository' (from 'huggingface_hub.repository') is deprecated and will be removed from version '1.0'. Please prefer the http-based alternatives instead. Given its large adoption in legacy code, the complete removal is only planned on next major release.
For more details, please read https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http.
  warnings.warn(warning_message, FutureWarning)
Traceback (most recent call last):
  File "/accounts/grad/robert_thompson/mllm/1_gpu_main.py", line 110, in <module>
    main()
  File "/accounts/grad/robert_thompson/mllm/1_gpu_main.py", line 75, in main
    trainer = Trainer(
              ^^^^^^^^
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/transformers/trainer.py", line 550, in __init__
    self.init_git_repo(at_init=True)
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/transformers/trainer.py", line 3497, in init_git_repo
    self.repo = Repository(self.args.output_dir, clone_from=repo_name, token=self.args.hub_token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/huggingface_hub/utils/_deprecation.py", line 132, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/huggingface_hub/repository.py", line 533, in __init__
    self.clone_from(repo_url=clone_from)
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/accounts/grad/robert_thompson/.local/lib/python3.11/site-packages/huggingface_hub/repository.py", line 723, in clone_from
    raise EnvironmentError(error_msg)
OSError: Tried to clone https://huggingface.co/mllm-dev/yelp_finetuned_sbatch_upload_1gpu_BIG in an unrelated git repository.
If you believe this is an error, please add a remote with the following URL: https://huggingface.co/mllm-dev/yelp_finetuned_sbatch_upload_1gpu_BIG.
Local path has its origin defined as: https://huggingface.co/mllm-dev/yelp_finetuned_sbatch_upload_4gpu_BIG

