Caution: the Python 3.8 module is intended for use on Ubuntu 20.04 machines, but most packages will probably work fine on Ubuntu 18.04.
ERROR: Unable to locate a modulefile for 'cuda/10.1'
Found existing installation: transformers 4.28.0
Uninstalling transformers-4.28.0:
  Would remove:
    /accounts/grad/robert_thompson/.local/bin/transformers-cli
    /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/transformers-4.28.0.dist-info/*
    /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/transformers/*
Proceed (Y/n)? ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 98, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 660, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 367, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 407, in _allowed_to_proceed
    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 190, in ask
    response = input(message)
EOFError: EOF when reading a line
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers==4.28.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (4.28.0)
Requirement already satisfied: filelock in /system/linux/anaconda3.8/lib/python3.8/site-packages (from transformers==4.28.0) (3.0.12)
Requirement already satisfied: packaging>=20.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from transformers==4.28.0) (21.3)
Requirement already satisfied: numpy>=1.17 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from transformers==4.28.0) (1.22.1)
Requirement already satisfied: pyyaml>=5.1 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from transformers==4.28.0) (5.4.1)
Requirement already satisfied: requests in /system/linux/anaconda3.8/lib/python3.8/site-packages (from transformers==4.28.0) (2.28.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from transformers==4.28.0) (0.21.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from transformers==4.28.0) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from transformers==4.28.0) (4.66.2)
Requirement already satisfied: regex!=2019.12.17 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from transformers==4.28.0) (2023.12.25)
Requirement already satisfied: fsspec>=2023.5.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.28.0) (2024.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.28.0) (4.3.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from packaging>=20.0->transformers==4.28.0) (3.0.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests->transformers==4.28.0) (1.26.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests->transformers==4.28.0) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests->transformers==4.28.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests->transformers==4.28.0) (2022.12.7)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: torch in /system/linux/anaconda3.8/lib/python3.8/site-packages (1.7.0+cu110)
Requirement already satisfied: dataclasses in /system/linux/anaconda3.8/lib/python3.8/site-packages (from torch) (0.8)
Requirement already satisfied: future in /system/linux/anaconda3.8/lib/python3.8/site-packages (from torch) (0.18.2)
Requirement already satisfied: typing-extensions in /system/linux/anaconda3.8/lib/python3.8/site-packages (from torch) (4.3.0)
Requirement already satisfied: numpy in /system/linux/anaconda3.8/lib/python3.8/site-packages (from torch) (1.22.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (2.18.0)
Requirement already satisfied: tqdm>=4.62.1 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets) (4.66.2)
Requirement already satisfied: requests>=2.19.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (2.28.1)
Requirement already satisfied: pyarrow>=12.0.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets) (15.0.0)
Requirement already satisfied: numpy>=1.17 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (1.22.1)
Requirement already satisfied: filelock in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (3.0.12)
Requirement already satisfied: aiohttp in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (3.7.4.post0)
Requirement already satisfied: fsspec[http]<=2024.2.0,>=2023.1.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets) (2024.2.0)
Requirement already satisfied: pyyaml>=5.1 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (5.4.1)
Requirement already satisfied: multiprocess in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (0.70.9)
Requirement already satisfied: xxhash in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets) (3.4.1)
Requirement already satisfied: pyarrow-hotfix in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets) (0.6)
Requirement already satisfied: packaging in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (21.3)
Requirement already satisfied: huggingface-hub>=0.19.4 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets) (0.21.3)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (0.3.1.1)
Requirement already satisfied: pandas in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets) (1.2.4)
Requirement already satisfied: attrs>=17.3.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets) (21.4.0)
Requirement already satisfied: typing-extensions>=3.6.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets) (4.3.0)
Requirement already satisfied: chardet<5.0,>=2.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets) (4.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets) (1.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets) (3.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from packaging->datasets) (3.0.6)
Requirement already satisfied: charset-normalizer<3,>=2 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (1.26.4)
Requirement already satisfied: idna<4,>=2.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2022.12.7)
Requirement already satisfied: python-dateutil>=2.7.3 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: evaluate in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (0.4.1)
Requirement already satisfied: tqdm>=4.62.1 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from evaluate) (4.66.2)
Requirement already satisfied: dill in /system/linux/anaconda3.8/lib/python3.8/site-packages (from evaluate) (0.3.1.1)
Requirement already satisfied: numpy>=1.17 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from evaluate) (1.22.1)
Requirement already satisfied: huggingface-hub>=0.7.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from evaluate) (0.21.3)
Requirement already satisfied: pandas in /system/linux/anaconda3.8/lib/python3.8/site-packages (from evaluate) (1.2.4)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from evaluate) (2024.2.0)
Requirement already satisfied: packaging in /system/linux/anaconda3.8/lib/python3.8/site-packages (from evaluate) (21.3)
Requirement already satisfied: datasets>=2.0.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from evaluate) (2.18.0)
Requirement already satisfied: multiprocess in /system/linux/anaconda3.8/lib/python3.8/site-packages (from evaluate) (0.70.9)
Requirement already satisfied: responses<0.19 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from evaluate) (0.18.0)
Requirement already satisfied: requests>=2.19.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from evaluate) (2.28.1)
Requirement already satisfied: xxhash in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from evaluate) (3.4.1)
Requirement already satisfied: pyyaml>=5.1 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (5.4.1)
Requirement already satisfied: pyarrow-hotfix in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: pyarrow>=12.0.0 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (15.0.0)
Requirement already satisfied: aiohttp in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (3.7.4.post0)
Requirement already satisfied: filelock in /system/linux/anaconda3.8/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (3.0.12)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.3.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from packaging->evaluate) (3.0.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2.1.0)
Requirement already satisfied: pytz>=2017.3 in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.6.3)
Requirement already satisfied: chardet<5.0,>=2.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (21.4.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (3.0.1)
Requirement already satisfied: six>=1.5 in /system/linux/anaconda3.8/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->evaluate) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /system/linux/anaconda3.8/lib/python3.8/site-packages (1.22.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: huggingface in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (0.0.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: regex in /accounts/grad/robert_thompson/.local/lib/python3.8/site-packages (2023.12.25)
/accounts/grad/robert_thompson/mllm
2024-03-04 16:42:12.920371: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-03-04 16:42:12.920371: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-03-04 16:42:12.920440: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-03-04 16:42:12.920439: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at openai-community/gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at openai-community/gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py:131: FutureWarning: 'Repository' (from 'huggingface_hub.repository') is deprecated and will be removed from version '1.0'. Please prefer the http-based alternatives instead. Given its large adoption in legacy code, the complete removal is only planned on next major release.
For more details, please read https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http.
  warnings.warn(warning_message, FutureWarning)
Traceback (most recent call last):
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/repository.py", line 674, in clone_from
    run_subprocess("git lfs install", self.local_dir)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/utils/_subprocess.py", line 83, in run_subprocess
    return subprocess.run(
  File "/usr/local/linux/anaconda3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'lfs', 'install']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main()
  File "main.py", line 67, in main
    trainer = Trainer(
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/transformers/trainer.py", line 550, in __init__
    self.init_git_repo(at_init=True)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/transformers/trainer.py", line 3497, in init_git_repo
    self.repo = Repository(self.args.output_dir, clone_from=repo_name, token=self.args.hub_token)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 132, in inner_f
    return f(*args, **kwargs)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/repository.py", line 533, in __init__
    self.clone_from(repo_url=clone_from)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/accounts/grad/robert_thompson/.local/lib/python3.8/site-packages/huggingface_hub/repository.py", line 726, in clone_from
    raise EnvironmentError(exc.stderr)
OSError: write /accounts/grad/robert_thompson/mllm/yelp_finetune_epoch_1_gpt2_1_parallel/.git/hooks/pre-push: disk quota exceeded
To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.

Traceback (most recent call last):
  File "/usr/local/linux/anaconda3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/linux/anaconda3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/linux/anaconda3.8/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/usr/local/linux/anaconda3.8/bin/python', '-u', 'main.py', '--local_rank=1']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
